<a href="https://colab.research.google.com/github/GuptaShivam007/Assignments/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [3]:
res=np.flip(arr)
print(res)

[5 4 6 3 2 1]


In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [14]:
count=np.bincount(x)
np.argmax(count)

1

In [16]:
ans=np.where(x==np.argmax(count))
print(ans)

(array([0, 5, 7, 8, 9]),)


In [22]:
count=np.bincount(y)
ans=np.where(y==np.argmax(count))
print(ans)
np.argmax(count)


(array([0, 1, 2]),)


1

In [24]:
mat = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
mat

matrix([[ 4,  1,  9],
        [12,  3,  1],
        [ 4,  5,  6]])

In [25]:
ans=mat.sum(axis=0)
print(ans)

[[20  9 16]]


In [26]:
ans=mat.sum(axis=1)
print(ans)

[[14]
 [16]
 [15]]
